/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.healthfirst.pims;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReportsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalesReport = new javax.swing.JButton();
        btnItemReport = new javax.swing.JButton();
        btnLowStock = new javax.swing.JButton();
        btnExpiry = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HealthFirst Reports");

        btnSalesReport.setText("Sales Report");
        btnSalesReport.addActionListener(this::btnSalesReportActionPerformed);

        btnItemReport.setText("Item-wise Report");
        btnItemReport.addActionListener(this::btnItemReportActionPerformed);

        btnLowStock.setText("Low Stock Report");
        btnLowStock.addActionListener(this::btnLowStockActionPerformed);

        btnExpiry.setText("Expiry Report");
        btnExpiry.addActionListener(this::btnExpiryActionPerformed);

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicine_ID", "Name", "Company", "Expiry Date"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSalesReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItemReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLowStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExpiry)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalesReport)
                    .addComponent(btnItemReport)
                    .addComponent(btnLowStock)
                    .addComponent(btnExpiry))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnLowStockActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String sql =
        "SELECT medicine_id, name, quantity_in_stock, reorder_level "
      + "FROM medicines "
      + "WHERE quantity_in_stock <= reorder_level "
      + "ORDER BY quantity_in_stock ASC";

DefaultTableModel model = new DefaultTableModel();
model.addColumn("ID");
model.addColumn("Medicine");
model.addColumn("Stock");
model.addColumn("Reorder Level");

try (Connection conn = DatabaseConnection.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql);
     ResultSet rs = pst.executeQuery()) {

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("medicine_id"),
            rs.getString("name"),
            rs.getInt("quantity_in_stock"),
            rs.getInt("reorder_level")
        });
    }

    tblReports.setModel(model);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Error loading low stock report: " + e.getMessage());
}
    }                                           

    private void btnSalesReportActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String sql = "SELECT sale_id, sale_date, total_amount "
           + "FROM sales ORDER BY sale_date DESC";

DefaultTableModel model = new DefaultTableModel();
model.addColumn("Sale ID");
model.addColumn("Date");
model.addColumn("Total Amount");

try (Connection conn = DatabaseConnection.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql);
     ResultSet rs = pst.executeQuery()) {

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("sale_id"),
            rs.getTimestamp("sale_date"),
            String.format("R %.2f", rs.getDouble("total_amount"))
        });
    }

    tblReports.setModel(model);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Error loading sales report: " + e.getMessage());
}
    }                                              

    private void btnItemReportActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String sql =
        "SELECT s.sale_id, m.name, si.quantity_sold, "
      + "si.price_at_sale, "
      + "(si.quantity_sold * si.price_at_sale) AS subtotal "
      + "FROM sale_items si "
      + "JOIN sales s ON si.sale_id = s.sale_id "
      + "JOIN medicines m ON si.medicine_id = m.medicine_id "
      + "ORDER BY s.sale_id DESC";

DefaultTableModel model = new DefaultTableModel();
model.addColumn("Sale ID");
model.addColumn("Medicine");
model.addColumn("Quantity");
model.addColumn("Price");
model.addColumn("Subtotal");

try (Connection conn = DatabaseConnection.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql);
     ResultSet rs = pst.executeQuery()) {

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("sale_id"),
            rs.getString("name"),
            rs.getInt("quantity_sold"),
            String.format("R %.2f", rs.getDouble("price_at_sale")),
            String.format("R %.2f", rs.getDouble("subtotal"))
        });
    }

    tblReports.setModel(model);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Error loading item-wise report: " + e.getMessage());
}
    }                                             

    private void btnExpiryActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String sql =
        "SELECT medicine_id, name, company, expiry_date "
      + "FROM medicines "
      + "ORDER BY expiry_date ASC";

DefaultTableModel model = new DefaultTableModel();
model.addColumn("ID");
model.addColumn("Medicine");
model.addColumn("Company");
model.addColumn("Expiry Date");

try (Connection conn = DatabaseConnection.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql);
     ResultSet rs = pst.executeQuery()) {

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("medicine_id"),
            rs.getString("name"),
            rs.getString("company"),
            rs.getDate("expiry_date")
        });
    }

    tblReports.setModel(model);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Error loading expiry report: " + e.getMessage());
}
    }                                         

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        AdminDashboard dashboard = new AdminDashboard();
dashboard.setLocationRelativeTo(null);
dashboard.setVisible(true);
this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExpiry;
    private javax.swing.JButton btnItemReport;
    private javax.swing.JButton btnLowStock;
    private javax.swing.JButton btnSalesReport;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReports;
    // End of variables declaration                   
}
